install:
	make -C spoofed-identifier install
	make -C unsigned install
	make -C valid-signature install

clean:
	make -C spoofed-identifier clean
	make -C unsigned clean
	make -C valid-signature clean
